---
## Starting Parameters for simulation
species: "Boar"
starting_population: 100
#Age range; once the Boar hits 5 years old, it cannot mate
age: [1,5]
# Starting percentages for age groups
age_percentage:
  young: 0.4
  adult: 0.5
  elder: 0.1
weight: [150, 400]
#Choose from poisson, binomial, beta, uniform, truncated_normal
age_distribution: uniform
weight_distribution: uniform
gene_edit_rate: 0.8
---
#Simulation parameters
newborn_survival_rate: 0.25
adult_survival_rate: 0.5